### ISSUE TITLE
belm trigger is broken

### ISSUE THREAD

**Issue by hoofdletterj** [jpmurray/laravel-eloquent-snippets#2]
The body for the belm trigger should have a > between "$this-" and "belongsToMany"

curronet body (v0.1.0): 
public function ${1:relationship}()\n{\n return $this-belongsToMany($1::class, ${2:table});\n}

should be: 
public function ${1:relationship}()\n{\n return $this->belongsToMany($1::class, ${2:table});\n}

**Comment by jpmurray** [comment]
Thank you! Just fixed it!

**Comment by hoofdletterj** [comment]
Superfast! :) Don't see it in the updates section of Atom though, should you add that yourself or would Atom pick it up soon?

**Comment by jpmurray** [comment]
AH! My bad, I forgot to publish it to APM! I thought it was picking new versions automatically! I'll be doing that in the coming minutes ;-)
